import Head from 'next/head'
import Sidebar from '../components/sidebar/Sidebar'
import Welcome from '../components/welcome/Welcome'

export default function Home () {
  return (
    <div>
      <Head>
        <title>New-project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex'>
        <Sidebar />
        <Welcome />
      </div>
    </div>
  )
}
